# ContainerFile used to create the image available at quay.io/qm-images/audio:latest
#
# How to build
# ==================
# podman login quay.io
# podman build -t quay.io/qm-images/audio:latest -f ContainerFile
# podman push quay.io/qm-images/audio:latest
FROM fedora:latest

RUN dnf -y install pulseaudio-utils alsa-utils procps-ng wireplumber pavucontrol \
    && dnf clean all && rm -rf /var/cache/dnf
CMD ["sleep", "infinity"]
