ARG FEDORA_VERSION=41

FROM fedora:${FEDORA_VERSION}

RUN dnf install -y dnf-plugins-core \
    && dnf -y update \
    && dnf install -y python3-devel \
    && dnf clean all

COPY server.py /usr/bin/ipc-server
CMD [ "ipc-server" ]
