---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/qm.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - make

actions:
  fix-spec-file:
    - bash .packit.sh

jobs:
  - job: copr_build
    trigger: pull_request
    # x86_64 is assumed by default
    # qm is noarch so we only need to test on one arch
    targets:
      - fedora-rawhide
      - fedora-latest
      - centos-stream-9

  # Run on commit to main branch
  - &copr
    job: copr_build
    trigger: commit
    branch: main
    owner: rhcontainerbot
    project: podman-next
    targets:
      - fedora-rawhide-aarch64
      - fedora-rawhide-ppc64le
      - fedora-rawhide-s390x
      - fedora-rawhide-x86_64
      - fedora-39-aarch64
      - fedora-39-ppc64le
      - fedora-39-s390x
      - fedora-39-x86_64
      - fedora-38-aarch64
      - fedora-38-ppc64le
      - fedora-38-s390x
      - fedora-38-x86_64
      - centos-stream+epel-next-9-aarch64
      - centos-stream+epel-next-9-ppc64le
      - centos-stream+epel-next-9-s390x
      - centos-stream+epel-next-9-x86_64

  - <<: *copr
    project: qm
    targets:
      - fedora-39-aarch64
      - fedora-39-ppc64le
      - fedora-39-x86_64
      - fedora-38-aarch64
      - fedora-38-ppc64le
      - fedora-38-x86_64
      - centos-stream-9-aarch64
      - centos-stream-9-ppc64le
      - centos-stream-9-x86_64

  - job: tests
    trigger: pull_request
    identifier: e2e
    tmt_plan: /tests/e2e/tier-0
    skip_build: true
    targets:
    - centos-stream-9-x86_64

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-rawhide
      - fedora-39
      - fedora-38
      - epel-9

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-rawhide
      - fedora-39
      - fedora-38
      - epel-9

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-39
      - fedora-38
      - epel-9
