---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/qm.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - make

actions:
  fix-spec-file:
    - bash .packit.sh

jobs:
  - &pr_job
    job: copr_build
    trigger: pull_request
    # x86_64 is assumed by default
    # qm is noarch so we only need to test on one arch
    targets: &pr_targets
      fedora-stable: {}
      epel-9:
        additional_repos:
          - copr://@centos-automotive-sig/bluechi-snapshot
      epel-10:
        additional_repos:
          - copr://@centos-automotive-sig/bluechi-snapshot

  # Run on commit to main branch
  - &copr
    job: copr_build
    trigger: commit
    branch: main
    owner: "@centos-automotive-sig"
    project: qm-next
    enable_net: true
    notifications:
      failure_comment:
        message: "QM build failed for merged commit {commit_sha}. Please check logs {logs_url}"

  - <<: *copr
    targets: &multiarch_targets
      - fedora-stable-aarch64
      - fedora-stable-ppc64le
      - fedora-stable-x86_64
      - epel-9-aarch64
      - epel-9-ppc64le
      - epel-9-x86_64
      - epel-10-aarch64
      - epel-10-ppc64le
      - epel-10-x86_64

  - job: tests
    trigger: pull_request
    identifier: e2e-multi-bluechi-agents
    tmt_plan: /plans/e2e/multi-bluechi-agents
    targets:
      - epel-9-x86_64
    manual_trigger: true
    tf_extra_params:
      environments:
        - artifacts:
            - &bluechi_copr_repo_c9s
              type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/centos-automotive-sig/bluechi-snapshot/repo/centos-stream-9
            - &bluechi_copr_repo_c10s
              type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/centos-automotive-sig/bluechi-snapshot/repo/centos-stream-10
            - &bluechi_copr_repo_fedora
              type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/centos-automotive-sig/bluechi-snapshot/repo/fedora
          hardware:
            disk:
              - size: ">= 20 GB"


  - job: tests
    trigger: pull_request
    identifier: e2e-ffi
    tmt_plan: /plans/e2e/ffi
    targets:
      - epel-9-x86_64
      - epel-10-x86_64
    tf_extra_params:
      environments:
        - artifacts:
            - *bluechi_copr_repo_c9s
            - *bluechi_copr_repo_c10s
          tmt:
            context:
              scenario: "ffi"
          hardware:
            disk:
              - size: ">= 20 GB"
              - size: ">= 20 GB"

  - job: tests
    trigger: pull_request
    identifier: qm-tier-0
    tmt_plan: /plans/e2e/tier-0
    targets:
      - epel-9-x86_64
      - epel-10-x86_64
    tf_extra_params:
      environments:
        - artifacts:
            - *bluechi_copr_repo_c9s
            - *bluechi_copr_repo_c10s
          hardware:
            disk:
              - size: ">= 20 GB"

  - job: tests
    trigger: pull_request
    identifier: kvm-tier-0
    tmt_plan: /plans/e2e/kvm-tier-0
    targets:
      - fedora-42-x86_64
      - epel-9-x86_64
    tf_extra_params:
      environments:
        - artifacts:
            - *bluechi_copr_repo_c9s
            - *bluechi_copr_repo_fedora
          hardware:
            disk:
              - size: ">= 20 GB"
            virtualization:
              is-supported: true

  - job: tests
    trigger: pull_request
    identifier: automotive-image-builder
    tmt_plan: /plans/e2e/aib
    targets:
      - epel-9-x86_64
    tf_extra_params:
      environments:
        hardware:
          disk:
            - size: ">= 20 GB"


  - job: propose_downstream
    trigger: release
    dist_git_branches: &downstream_branches
      - fedora-all
      - epel-9
      - epel-10

  - job: koji_build
    trigger: commit
    dist_git_branches: *downstream_branches

  - job: bodhi_update
    trigger: commit
    dist_git_branches: &bodhi_branches
      # rawhide updates are created automatically
      - fedora-branched
      - epel-9
      - epel-10

  # QM Wayland package
  - job: copr_build
    trigger: pull_request
    identifier: qm-wayland
    specfile_path: rpm/wayland/qm-wayland.spec
    actions:
      fix-spec-file:
        - bash .packit-wayland.sh
    targets: *pr_targets

  - <<: *copr
    identifier: qm-wayland-main
    specfile_path: rpm/wayland/qm-wayland.spec
    actions:
      fix-spec-file:
        - bash .packit-wayland.sh
    targets: *multiarch_targets
    notifications:
      failure_comment:
        message: "QM Wayland build failed for merged commit {commit_sha}. Please check logs {logs_url}"

  # Downstream jobs for qm-wayland
  - job: propose_downstream
    trigger: release
    identifier: qm-wayland-downstream
    specfile_path: rpm/wayland/qm-wayland.spec
    dist_git_branches: *downstream_branches

  - job: koji_build
    trigger: commit
    identifier: qm-wayland-koji
    specfile_path: rpm/wayland/qm-wayland.spec
    dist_git_branches: *downstream_branches

  - job: bodhi_update
    trigger: commit
    identifier: qm-wayland-bodhi
    specfile_path: rpm/wayland/qm-wayland.spec
    dist_git_branches: *bodhi_branches
