# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/qm.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - make

actions:
  fix-spec-file:
    - bash .packit.sh

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      fedora-development: {}
      fedora-latest: {}
      epel-9:
        additional_repos:
          - copr://@centos-automotive-sig/bluechi-snapshot

  - &copr
    job: copr_build
    trigger: commit
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  - <<: *copr
    project: qm
    targets:
      - fedora-stable-aarch64
      - fedora-stable-ppc64le
      - fedora-stable-x86_64
      - epel-9-aarch64
      - epel-9-ppc64le
      - epel-9-x86_64

  # Testing jobs with setup script execution
  - job: tests
    trigger: pull_request
    identifier: e2e-multi-bluechi-agents
    tmt_plan: /plans/e2e/multi-bluechi-agents
    targets:
      - epel-9-x86_64
    manual_trigger: true
    tf_extra_params:
      environments:
        - artifacts:
            - &bluechi_copr_repo
              type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/centos-automotive-sig/bluechi-snapshot/repo/centos-stream-9
          hardware:
            disk:
              - size: ">= 20 GB"
    tests:
      - name: Run Setup Script
        run:
          script: |
            sudo dnf install -y qm
            # Execute the setup script and check if it succeeds
            if /usr/share/qm/setup; then
              echo "Setup script executed successfully with return code 0."
            else
              echo "Setup script failed with a non-zero return code."
              exit 1

  - job: tests
    trigger: pull_request
    identifier: e2e-ffi
    tmt_plan: /plans/e2e/ffi
    targets:
      - epel-9-x86_64
    tf_extra_params:
      environments:
        - artifacts:
            - *bluechi_copr_repo
          hardware:
            disk:
              - size: ">= 20 GB"
    tests:
      - name: Run Setup Script
        run:
          script: |
            sudo dnf install -y qm
            if /usr/share/qm/setup; then
              echo "Setup script executed successfully."
            else
              echo "Setup script failed with a non-zero return code."
              exit 1

  - job: tests
    trigger: pull_request
    identifier: qm-tier-0
    tmt_plan: /plans/e2e/tier-0
    targets:
      - epel-9-x86_64
    tf_extra_params:
      environments:
        - artifacts:
            - *bluechi_copr_repo
          hardware:
            disk:
              - size: ">= 20 GB"
    tests:
      - name: Run Setup Script
        run:
          script: |
            sudo dnf install -y qm
            if /usr/share/qm/setup; then
              echo "Setup script executed successfully."
            else
              echo "Setup script failed with a non-zero return code."
              exit 1

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all
      - epel-9

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
      - epel-9

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
      - epel-9
