---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/qm.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - make

actions:
  fix-spec-file:
    - bash .packit.sh

jobs:
  - job: copr_build
    trigger: pull_request
    # x86_64 is assumed by default
    # qm is noarch so we only need to test on one arch
    targets:
      fedora-development: {}
      fedora-latest: {}
      epel-9:
        additional_repos:
          - copr://@centos-automotive-sig/bluechi-snapshot
      epel-10:
        additional_repos:
          - copr://@centos-automotive-sig/bluechi-snapshot

  # Run on commit to main branch
  - &copr
    job: copr_build
    trigger: commit
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  - <<: *copr
    project: qm
    targets:
      - fedora-stable-aarch64
      - fedora-stable-ppc64le
      - fedora-stable-x86_64
      - epel-9-aarch64
      - epel-9-ppc64le
      - epel-9-x86_64
      - epel-10-aarch64
      - epel-10-ppc64le
      - epel-10-x86_64

  - job: tests
    trigger: pull_request
    identifier: e2e-multi-bluechi-agents
    tmt_plan: /plans/e2e/multi-bluechi-agents
    targets:
      - epel-9-x86_64
    manual_trigger: true
    tf_extra_params:
      environments:
        - artifacts:
          - &bluechi_copr_repo
            type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/g/centos-automotive-sig/bluechi-snapshot/repo/centos-stream-9
          - &bluechi_copr_repo_fedora
            type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/g/centos-automotive-sig/bluechi-snapshot/repo/fedora
          hardware:
            disk:
             - size: ">= 20 GB"


  - job: tests
    trigger: pull_request
    identifier: e2e-ffi
    tmt_plan: /plans/e2e/ffi
    targets:
      - epel-9-x86_64
    tf_extra_params:
      environments:
        - artifacts:
          - *bluechi_copr_repo
          tmt:
            context:
             scenario : "ffi"
          hardware:
            disk:
             - size: ">= 20 GB"
             - size: ">= 20 GB"

  - job: tests
    trigger: pull_request
    identifier: qm-tier-0
    tmt_plan: /plans/e2e/tier-0
    targets:
      - epel-9-x86_64
    tf_extra_params:
      environments:
        - artifacts:
          - *bluechi_copr_repo
          hardware:
            disk:
             - size: ">= 20 GB"

  - job: tests
    trigger: pull_request
    identifier: kvm-tier-0
    tmt_plan: /plans/e2e/kvm-tier-0
    targets:
      # TBF: fedora-latest -eq 42 no published to public-tf
      - fedora-41
      - epel-9-x86_64
    tf_extra_params:
      environments:
        - artifacts:
          - *bluechi_copr_repo_fedora
          hardware:
            disk:
             - size: ">= 20 GB"
            virtualization:
             is-supported: true

  - job: tests
    trigger: pull_request
    identifier: automotive-image-builder
    tmt_plan: /plans/e2e/aib
    targets:
      - epel-9-x86_64
    tf_extra_params:
      environments:
          hardware:
            disk:
             - size: ">= 20 GB"


  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all
      - epel-9
      - epel-10

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
      - epel-9
      - epel-10

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-branched
      - epel-9
      - epel-10
