# ContainerFile used to create the image available at quay.io/qm-images/multimedia:latest
#
# How to build
# ==================
# podman build -t quay.io/qm-images/multimedia:latest -f ContainerFile
#
FROM fedora:latest

# ContainerFile to install multimedia tools

# Additional repos for gstreamer plugins
RUN dnf install -y fswebcam

# Set CMD to bash so you can manually run tools
CMD ["bash"]
