# Containerfile (build-time)
FROM fedora:latest

RUN dnf -y update && \
    dnf -y install git python3 python3-pip podman which && \
    dnf clean all

COPY qm-autoware /tmp
RUN chmod +x /tmp/qm-autoware

CMD ["/tmp/qm-autoware"]
