ARG TAG=latest
FROM quay.io/centos/centos:stream10

RUN dnf -y update \
    && dnf -y install dnf-plugins-core \
    && dnf config-manager --set-enabled crb \
    && dnf -y install epel-release \
    && dnf -y install weston \
    && dnf clean all && rm -rf /var/cache/dnf
