# ContainerFile used to create the image available at quay.io/qm-images/wm_mutter:latest
#
# How to build
# ==================
# podman login quay.io
# podman build -t quay.io/qm-images/wm_mutter:latest -f ContainerFile
# podman push quay.io/qm-images/wm_mutter:latest
FROM fedora:40

RUN dnf -y install weston                                                      \
    && dnf clean all && rm -rf /var/cache/dnf
