#!/bin/bash
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# This tools is a workaround regarding the issue found in ostree image only
# report via GitHub: https://github.com/containers/qm/issues/367

# Path to the qm.container
FILE="/usr/share/containers/systemd/qm.container"

# Check for the presence of the string and if "Timezone=local" is already commented
if ! grep -q "# WIP - Github Issue#367" "$FILE" && ! grep -q "# Timezone=local" "$FILE"; then
    # Make changes if the strings do not exist
    sed -i '/Timezone=local/ {
        i # WIP - Github Issue#367
        i # See https://github.com/containers/qm/issues/367 for more info.
        s/^Timezone=local/# &/; # Comments the line that matches Timezone=local
        a Environment=TZ
    }' "$FILE"
fi
