site_name: QM Documentation

repo_url: https://github.com/containers/qm
repo_name: qm
edit_uri: blob/main/docs/docs/

copyright: Copyright Contributors to the QM project
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting_started/installation.md
  - Additional resources: resources.md

theme:
  name: material
  features:
    - content.code.copy
    - navigation.indexes

extra_javascript:
  - assets/js/tab-sync.js

markdown_extensions:
  - toc:
      permalink: True
  - sane_lists
  - smarty
  - admonition
  - pymdownx.snippets:
      base_path: ["docs"]
      check_paths: True
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
