#!/bin/bash

if [ ! -d /lib/modules ]; then
   echo "FATAL: /lib/modules: No such file or directory"
   exit 1
fi

if [ -n "$(ls -A /lib/modules)" ]; then
   echo "This folder should be empty, any modules cannot load via modprobe"
   exit 1
fi

# Modprobe module ext4
modprobe ext4

# Access module file
ls $(modprobe ext4 2>&1 >/dev/null | cut -d ' ' -f 9)

echo "done"
