name: Check Cgroup Version

on: [push, pull_request]  # Trigger on push or pull request. Adjust as needed.

jobs:
  check-cgroup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check cgroup version
        run: |
          echo "Checking cgroup version and settings..."
          grep cgroup /proc/filesystems
          mount | grep cgroup
          cat /proc/cgroups
          cat /sys/fs/cgroup/cgroup.controllers
